// packages/terminal-react/src/ui/Switch.tsx
import React from "react";
import * as SwitchPrimitive from "@radix-ui/react-switch";
import { SwitchClass, type SwitchClassProps } from "@ui/cva";
import { ClassNameValue, twMerge } from "tailwind-merge";

interface SwitchProps
	extends React.ComponentPropsWithoutRef<typeof SwitchPrimitive.Root> {
	variant?: SwitchClassProps["variant"];
	size?: SwitchClassProps["size"];
}

export const Switch = React.forwardRef<
	React.ElementRef<typeof SwitchPrimitive.Root>,
	SwitchProps
>(({ className, variant, size, ...props }, ref) => (
	<SwitchPrimitive.Root
		className={twMerge(
			SwitchClass({ size, variant, component: "root" }) as ClassNameValue,
			className
		)}
		{...props}
		ref={ref}
	>
		<SwitchPrimitive.Thumb
			className={twMerge(
				SwitchClass({ size, variant, component: "thumb" }) as ClassNameValue,
				className
			)}
		/>
	</SwitchPrimitive.Root>
));

// packages/terminal-vue/src/components/ui/Switch.vue
<script setup lang="ts">
import { SwitchRoot, SwitchThumb } from 'radix-vue'
import { SwitchClass, type SwitchClassProps } from "@/components/ui/cva"
import { useVModel } from "@vueuse/core";

type SwitchProps = InstanceType<typeof SwitchRoot>["$props"] & SwitchClassProps;

const props = withDefaults(defineProps<SwitchProps>(), {
  open: undefined,
});

const emit = defineEmits(["update:open"]);

const open = useVModel(props, "open", emit, {
  defaultValue: props.defaultOpen,
  passive: true,
});
</script>

<template>
  <SwitchRoot v-model:open="open" :class="SwitchClass({ size, variant, component: 'root' })">
    <SwitchThumb :class="SwitchClass({ size, variant, component: 'thumb' })" />
  </SwitchRoot>
</template>
